version: '2'
services:
  cleansample-postgres:
    build: ./postgres
    image: cbn/cleansample-postgres
    ports:
      - '5432:5432'
    volumes:
      - ~/cleansample/postgresql/data/:/var/lib/postgresql/data:Z
